class GraphNode {
    constructor(name, type, x_coor, y_coor) {
        this.name = name;
        this.type = type;
        this.neighbors = [];
        this.x_coor = x_coor;
        this.y_coor = y_coor;
    }
    addNeighbor(node) {
        if (!this.neighbors.includes(node)) this.neighbors.push(node);
    }
    addBidirectionalNeighbor(node) {
        this.addNeighbor(node);
        node.addNeighbor(this);
    }
}

class GraphDatabase {
    constructor() {
        this.graph = new Map();
        this.buildGraph();
    }

    buildGraph() {
        // Created Nodes
        // — buildings —
        const School_of_Engineering = new GraphNode("School of Engineering (SOE)", "building", 1825, 1705);
        const School_of_Computing_and_ = new GraphNode("School of Computing and Information Technology (SCIT)", "building", 1572, 1795);
        const College_of_Health_Scienc = new GraphNode("College of Health Sciences (COHS)", "building", 1443, 2148);
        const Faculty_of_Built_Environ = new GraphNode("Faculty of Built Environment (FOBE)", "building", 1074, 2122);
        const School_of_Business_Admin = new GraphNode("School of Business Administration (SOBA)", "building", 1323, 1970);
        const College_of_Business_Mana = new GraphNode("College of Business and Management (COBAM)", "building", 1245, 1857);
        const Faculty_of_Sports_and_Sc = new GraphNode("Faculty of Sports and Science (FOSS)", "building", 254, 2993);
        const Faculty_of_Education_and = new GraphNode("Faculty of Education and Liberal Studies (FELS)", "building", 1353, 1602);
        const Main_Administration_Buil = new GraphNode("Main Administration Building", "building", 1577, 1914);
        const Student_Union_Business_O = new GraphNode("Student Union Business Office", "building", 1248, 1228);
        const Nursing_Department = new GraphNode("Nursing Department", "building", 908, 820);
        const School_of_Hospitality_an = new GraphNode("School of Hospitality and Tourism Management (SHTM)", "building", 1235, 1073);
        const Computing_and_Engineerin = new GraphNode("Computing and Engineering Entrepreneurial Centre (CEEC)", "building", 1945, 1810);
        const Shared_Facilities = new GraphNode("Shared Facilities", "building", 695, 1639);
        const Drawing_Room = new GraphNode("Drawing Room", "building", 1530, 1255);
        const Chapel = new GraphNode("Chapel", "building", 1337, 1291);
        const Auditorium = new GraphNode("Auditorium", "building", 1260, 459);
        const Calvin_McKain_Library = new GraphNode("Calvin McKain Library", "building", 1546, 2677);
        const The_Barn_UTech_Student_A = new GraphNode("The Barn - UTech Student Activity Centre", "building", 604, 1125);
        const Hotel = new GraphNode("Hotel", "building", 904, 1067);
        const Burger_King = new GraphNode("Burger King (BK)", "building", 1012, 1250);
        const Juici_Patties = new GraphNode("Juici Patties", "building", 1409, 952);
        const Office_of_Admissions_and = new GraphNode("Office of Admissions and Enrolment Management", "building", 2036, 971);
        const Student_Services_Buildin = new GraphNode("Student Services Building", "building", 1696, 1003);
        const Sculpture_Park = new GraphNode("Sculpture Park", "building", 1363, 1371);
        const NCB = new GraphNode("NCB", "building", 1475, 939);
        const Scholarship_Unit = new GraphNode("Scholarship Unit", "building", 1852, 757);
        const Andrea_Groceries = new GraphNode("Andrea Groceries", "building", 1288, 866);
        const Faculty_of_Law = new GraphNode("Faculty of Law (FOL)", "building", 2023, 648);

        // — gates —
        const First_Gate = new GraphNode("First Gate", "gate", 1284, 3123);
        const Back_Gate = new GraphNode("Back Gate", "gate", 2134, 58);
        const Second_Gate = new GraphNode("Second Gate", "gate", 1718, 3173);

        // — walkways —
        const WN_MAIN_01 = new GraphNode("WN-MAIN-01", "walkway", 1318, 2917);
        const WN_MAIN_02 = new GraphNode("WN-MAIN-02", "walkway", 1354, 2742);
        const WN_MAIN_03 = new GraphNode("WN-MAIN-03", "walkway", 1334, 2600);
        const WN_SECOND_01 = new GraphNode("WN-SECOND-01", "walkway", 1723, 3038);
        const WN_SECOND_02 = new GraphNode("WN-SECOND-02", "walkway", 1742, 2764);
        const WN_CML_01 = new GraphNode("WN-CML-01", "walkway", 1496, 2895);
        const WN_CML_03 = new GraphNode("WN-CML-03", "walkway", 1642, 2687);
        const WN_CHS_01 = new GraphNode("WN-CHS-01", "walkway", 1498, 2093);
        const WN_CHS_02 = new GraphNode("WN-CHS-02", "walkway", 1646, 2163);
        const WN_CHS_03 = new GraphNode("WN-CHS-03", "walkway", 1395, 2155);
        const WN_FBE_01 = new GraphNode("WN-FBE-01", "walkway", 1172, 2179);
        const WN_FBE_02 = new GraphNode("WN-FBE-02", "walkway", 817, 2203);
        const WN_FBE_03 = new GraphNode("WN-FBE-03", "walkway", 1177, 2107);
        const WN_CBM_02 = new GraphNode("WN-CBM-02", "walkway", 1272, 1916);
        const WN_MAB_03 = new GraphNode("WN-MAB-03", "walkway", 1650, 1928);
        const WN_SBA_01 = new GraphNode("WN-SBA-01", "walkway", 1330, 1930);
        const WN_SBA_02 = new GraphNode("WN-SBA-02", "walkway", 1174, 2013);
        const WN_SOE_01 = new GraphNode("WN-SOE-01", "walkway", 1837, 1522);
        const WN_SOE_02 = new GraphNode("WN-SOE-02", "walkway", 1746, 1620);
        const WN_SOE_03 = new GraphNode("WN-SOE-03", "walkway", 1750, 1709);
        const WN_SCIT_01 = new GraphNode("WN-SCIT-01", "walkway", 1572, 1681);
        const WN_SCIT_02 = new GraphNode("WN-SCIT-02", "walkway", 1520, 1743);
        const WN_SCIT_03 = new GraphNode("WN-SCIT-03", "walkway", 1701, 1656);
        const WN_FELS_01 = new GraphNode("WN-FELS-01", "walkway", 1356, 1550);
        const WN_FELS_02 = new GraphNode("WN-FELS-02", "walkway", 1567, 1625);
        const WN_CEEC_01 = new GraphNode("WN-CEEC-01", "walkway", 1880, 1834);
        const WN_CEEC_02 = new GraphNode("WN-CEEC-02", "walkway", 1969, 1757);
        const WN_CENTRAL_01 = new GraphNode("WN-CENTRAL-01", "walkway", 1242, 1705);
        const WN_CENTRAL_02 = new GraphNode("WN-CENTRAL-02", "walkway", 1539, 1487);
        const WN_CENTRAL_03 = new GraphNode("WN-CENTRAL-03", "walkway", 1305, 1397);
        const WN_DR_01 = new GraphNode("WN-DR-01", "walkway", 1619, 1235);
        const WN_DR_02 = new GraphNode("WN-DR-02", "walkway", 1589, 1280);
        const WN_CHPL_01 = new GraphNode("WN-CHPL-01", "walkway", 1287, 1297);
        const WN_CHPL_02 = new GraphNode("WN-CHPL-02", "walkway", 1105, 1359);
        const WN_SP_01 = new GraphNode("WN-SP-01", "walkway", 1358, 1515);
        const WN_SP_02 = new GraphNode("WN-SP-02", "walkway", 1280, 1331);
        const WN_SUBO_01 = new GraphNode("WN-SUBO-01", "walkway", 1260, 1193);
        const WN_SUBO_02 = new GraphNode("WN-SUBO-02", "walkway", 1268, 1264);
        const WN_BK_01 = new GraphNode("WN-BK-01", "walkway", 1082, 1246);
        const WN_AG_01 = new GraphNode("WN-AG-01", "walkway", 1234, 832);
        const WN_HOTEL_01 = new GraphNode("WN-HOTEL-01", "walkway", 803, 946);
        const WN_HOTEL_02 = new GraphNode("WN-HOTEL-02", "walkway", 891, 1163);
        const WN_ND_01 = new GraphNode("WN-ND-01", "walkway", 920, 910);
        const WN_JP_01 = new GraphNode("WN-JP-01", "walkway", 1423, 1035);
        const WN_JP_02 = new GraphNode("WN-JP-02", "walkway", 1396, 861);
        const WN_SHTM_01 = new GraphNode("WN-SHTM-01", "walkway", 1262, 984);
        const WN_SHTM_02 = new GraphNode("WN-SHTM-02", "walkway", 1168, 1178);
        const WN_SHTM_03 = new GraphNode("WN-SHTM-03", "walkway", 1247, 1168);
        const WN_SSB_01 = new GraphNode("WN-SSB-01", "walkway", 1714, 924);
        const WN_SSB_02 = new GraphNode("WN-SSB-02", "walkway", 1755, 1038);
        const WN_OAE_01 = new GraphNode("WN-OAE-01", "walkway", 1864, 986);
        const WN_OAE_02 = new GraphNode("WN-OAE-02", "walkway", 1926, 905);
        const WN_OAE_03 = new GraphNode("WN-OAE-03", "walkway", 1993, 1108);
        const WN_AUD_01 = new GraphNode("WN-AUD-01", "walkway", 1290, 585);
        const WN_AUD_02 = new GraphNode("WN-AUD-02", "walkway", 1366, 352);
        const WN_AUD_03 = new GraphNode("WN-AUD-03", "walkway", 1133, 417);
        const WN_BG_01 = new GraphNode("WN-BG-01", "walkway", 2089, 193);
        const WN_BG_02 = new GraphNode("WN-BG-02", "walkway", 2068, 391);
        const WN_SL_01 = new GraphNode("WN-SL-01", "walkway", 2005, 605);
        const WN_SL_02 = new GraphNode("WN-SL-02", "walkway", 1857, 658);
        const WN_SL_03 = new GraphNode("WN-SL-03", "walkway", 1947, 714);
        const WN_BARN_02 = new GraphNode("WN-BARN-02", "walkway", 659, 956);
        const WN_BARN_03 = new GraphNode("WN-BARN-03", "walkway", 812, 1215);
        const WN_SF_01 = new GraphNode("WN-SF-01", "walkway", 756, 1403);
        const WN_SF_02 = new GraphNode("WN-SF-02", "walkway", 510, 1629);
        const WN_SF_03 = new GraphNode("WN-SF-03", "walkway", 821, 1612);
        const WN_FSS_01 = new GraphNode("WN-FSS-01", "walkway", 582, 2863);
        const WN_FSS_02 = new GraphNode("WN-FSS-02", "walkway", 141, 2963);
        const WN_FSS_03 = new GraphNode("WN-FSS-03", "walkway", 431, 2979);
        const WN_JB_01 = new GraphNode("WN-JB-01", "walkway", 1293, 2494);
        const WN_JB_02 = new GraphNode("WN-JB-02", "walkway", 1313, 2190);
        const WN_JB_03 = new GraphNode("WN-JB-03", "walkway", 1321, 2108);
        const WN_JB_04 = new GraphNode("WN-JB-04", "walkway", 1355, 1877);
        const WN_JB_05 = new GraphNode("WN-JB-05", "walkway", 1355, 1707);
        const WN_JB_06 = new GraphNode("WN-JB-06", "walkway", 1358, 1471);
        const WN_JB_07 = new GraphNode("WN-JB-07", "walkway", 1426, 1304);
        const WN_JB_08 = new GraphNode("WN-JB-08", "walkway", 1434, 1145);
        const WN_JB_09 = new GraphNode("WN-JB-09", "walkway", 1287, 837);
        const WN_HR_01 = new GraphNode("WN-HR-01", "walkway", 783, 1726);
        const WN_HR_02 = new GraphNode("WN-HR-02", "walkway", 1111, 1970);
        const WN_HR_03 = new GraphNode("WN-HR-03", "walkway", 1509, 1998);
        const WN_HR_04 = new GraphNode("WN-HR-04", "walkway", 1392, 1934);
        const WN_UCR_01 = new GraphNode("WN-UCR-01", "walkway", 1492, 648);
        const WN_UCR_02 = new GraphNode("WN-UCR-02", "walkway", 1609, 640);
        const WN_UCR_03 = new GraphNode("WN-UCR-03", "walkway", 1782, 615);
        const WN_UCR_04 = new GraphNode("WN-UCR-04", "walkway", 1932, 648);
        const WN_UCR_05 = new GraphNode("WN-UCR-05", "walkway", 1204, 684);
        const WN_UCR_07 = new GraphNode("WN-UCR-07", "walkway", 1000, 702);
        const WN_UCR_08 = new GraphNode("WN-UCR-08", "walkway", 801, 736);
        const WN_ESR_01 = new GraphNode("WN-ESR-01", "walkway", 2013, 1241);
        const WN_ESR_02 = new GraphNode("WN-ESR-02", "walkway", 1852, 1385);
        const WN_ESR_03 = new GraphNode("WN-ESR-03", "walkway", 2023, 1590);
        const WN_ESR_04 = new GraphNode("WN-ESR-04", "walkway", 1993, 1895);
        const WN_ESR_05 = new GraphNode("WN-ESR-05", "walkway", 1945, 2187);
        const WN_WCR_01 = new GraphNode("WN-WCR-01", "walkway", 708, 1252);
        const WN_WCR_02 = new GraphNode("WN-WCR-02", "walkway", 660, 1733);
        const WN_WCR_03 = new GraphNode("WN-WCR-03", "walkway", 777, 1926);
        const WN_WCR_04 = new GraphNode("WN-WCR-04", "walkway", 761, 2374);
        const WN_WCR_05 = new GraphNode("WN-WCR-05", "walkway", 675, 2640);
        const WN_SB_01 = new GraphNode("WN-SB-01", "walkway", 1707, 2691);
        const WN_SB_02 = new GraphNode("WN-SB-02", "walkway", 1703, 2611);
        const WN_SB_03 = new GraphNode("WN-SB-03", "walkway", 1699, 2473);
        const WN_SB_04 = new GraphNode("WN-SB-04", "walkway", 1691, 2299);
        const WN_CCC_01 = new GraphNode("WN-CCC-01", "walkway", 850, 1553);
        const WN_CCC_02 = new GraphNode("WN-CCC-02", "walkway", 988, 1553);
        const WN_CCC_03 = new GraphNode("WN-CCC-03", "walkway", 1134, 1610);
        const WN_CCC_04 = new GraphNode("WN-CCC-04", "walkway", 1709, 1467);
        const WN_CCC_05 = new GraphNode("WN-CCC-05", "walkway", 1681, 1341);
        const WN_SWC_01 = new GraphNode("WN-SWC-01", "walkway", 680, 2353);
        const WN_SWC_02 = new GraphNode("WN-SWC-02", "walkway", 473, 2302);
        const WN_SWC_04 = new GraphNode("WN-SWC-04", "walkway", 463, 2018);
        const WN_SWC_05 = new GraphNode("WN-SWC-05", "walkway", 493, 1881);
        const WN_NEC_01 = new GraphNode("WN-NEC-01", "walkway", 1664, 1204);
        const WN_NEC_02 = new GraphNode("WN-NEC-02", "walkway", 1791, 1082);
        const WN_NEC_03 = new GraphNode("WN-NEC-03", "walkway", 1962, 826);
        const WN_NEC_04 = new GraphNode("WN-NEC-04", "walkway", 2057, 532);
        const WN_NEC_05 = new GraphNode("WN-NEC-05", "walkway", 2073, 299);
        const WN_CML_02 = new GraphNode("WN-CML-02", "walkway", 1612, 2590);
        const WN_SB_05 = new GraphNode("WN-SB-05", "walkway", 1700, 2158);
        const WN_DC_01 = new GraphNode("WN-DC-01", "walkway", 764, 2053);
        const WN_DC_02 = new GraphNode("WN-DC-02", "walkway", 1022, 2050);
        const WN_DC_03 = new GraphNode("WN-DC-03", "walkway", 1079, 1783);
        const WN_SBA_03 = new GraphNode("WN-SBA-03", "walkway", 1332, 2008);
        const WN_SOE_04 = new GraphNode("WN-SOE-04", "walkway", 1749, 1951);
        const WN_DC_04 = new GraphNode("WN-DC-04", "walkway", 857, 2057);
        const WN_SF_04 = new GraphNode("WN-SF-04", "walkway", 690, 1526);
        const WN_GA_01 = new GraphNode("WN-GA-01", "walkway", 852, 1206);
        const WN_GA_02 = new GraphNode("WN-GA-02", "walkway", 1000, 863);
        const WN_SHTM_04 = new GraphNode("WN-SHTM-04", "walkway", 1090, 1052);
        const WN_JB_10 = new GraphNode("WN-JB-10", "walkway", 1077, 1188);
        const WN_BA_01 = new GraphNode("WN-BA-01", "walkway", 1250, 1540);
        const WN_BA_02 = new GraphNode("WN-BA-02", "walkway", 982, 1607);
        const WN_JB_11 = new GraphNode("WN-JB-11", "walkway", 562, 1373);
        const WN_MAB_04 = new GraphNode("WN-MAB-04", "walkway", 1642, 2006);
        const WN_STA_01 = new GraphNode("WN-STA-01", "walkway", 1685, 751);
        const WN_STA_02 = new GraphNode("WN-STA-02", "walkway", 1600, 886);
        const WN_STA_03 = new GraphNode("WN-STA-03", "walkway", 1554, 1121);
        const WN_SHTM_05 = new GraphNode("WN-SHTM-05", "walkway", 1327, 1161);
        const WN_NCB_01 = new GraphNode("WN-NCB-01", "walkway", 1521, 938);

        // Add to graph
        this.graph.set("School of Engineering (SOE)", School_of_Engineering);
        this.graph.set("School of Computing and Information Technology (SCIT)", School_of_Computing_and_);
        this.graph.set("College of Health Sciences (COHS)", College_of_Health_Scienc);
        this.graph.set("Faculty of Built Environment (FOBE)", Faculty_of_Built_Environ);
        this.graph.set("School of Business Administration (SOBA)", School_of_Business_Admin);
        this.graph.set("College of Business and Management (COBAM)", College_of_Business_Mana);
        this.graph.set("Faculty of Sports and Science (FOSS)", Faculty_of_Sports_and_Sc);
        this.graph.set("Faculty of Education and Liberal Studies (FELS)", Faculty_of_Education_and);
        this.graph.set("Main Administration Building", Main_Administration_Buil);
        this.graph.set("Student Union Business Office", Student_Union_Business_O);
        this.graph.set("Nursing Department", Nursing_Department);
        this.graph.set("School of Hospitality and Tourism Management (SHTM)", School_of_Hospitality_an);
        this.graph.set("Computing and Engineering Entrepreneurial Centre (CEEC)", Computing_and_Engineerin);
        this.graph.set("Shared Facilities", Shared_Facilities);
        this.graph.set("Drawing Room", Drawing_Room);
        this.graph.set("Chapel", Chapel);
        this.graph.set("Auditorium", Auditorium);
        this.graph.set("Calvin McKain Library", Calvin_McKain_Library);
        this.graph.set("The Barn - UTech Student Activity Centre", The_Barn_UTech_Student_A);
        this.graph.set("Hotel", Hotel);
        this.graph.set("Burger King (BK)", Burger_King);
        this.graph.set("Juici Patties", Juici_Patties);
        this.graph.set("Office of Admissions and Enrolment Management", Office_of_Admissions_and);
        this.graph.set("Student Services Building", Student_Services_Buildin);
        this.graph.set("Sculpture Park", Sculpture_Park);
        this.graph.set("NCB", NCB);
        this.graph.set("Scholarship Unit", Scholarship_Unit);
        this.graph.set("First Gate", First_Gate);
        this.graph.set("Back Gate", Back_Gate);
        this.graph.set("Second Gate", Second_Gate);
        this.graph.set("WN-MAIN-01", WN_MAIN_01);
        this.graph.set("WN-MAIN-02", WN_MAIN_02);
        this.graph.set("WN-MAIN-03", WN_MAIN_03);
        this.graph.set("WN-SECOND-01", WN_SECOND_01);
        this.graph.set("WN-SECOND-02", WN_SECOND_02);
        this.graph.set("WN-CML-01", WN_CML_01);
        this.graph.set("WN-CML-03", WN_CML_03);
        this.graph.set("WN-CHS-01", WN_CHS_01);
        this.graph.set("WN-CHS-02", WN_CHS_02);
        this.graph.set("WN-CHS-03", WN_CHS_03);
        this.graph.set("WN-FBE-01", WN_FBE_01);
        this.graph.set("WN-FBE-02", WN_FBE_02);
        this.graph.set("WN-FBE-03", WN_FBE_03);
        this.graph.set("WN-CBM-02", WN_CBM_02);
        this.graph.set("WN-MAB-03", WN_MAB_03);
        this.graph.set("WN-SBA-01", WN_SBA_01);
        this.graph.set("WN-SBA-02", WN_SBA_02);
        this.graph.set("WN-SOE-01", WN_SOE_01);
        this.graph.set("WN-SOE-02", WN_SOE_02);
        this.graph.set("WN-SOE-03", WN_SOE_03);
        this.graph.set("WN-SCIT-01", WN_SCIT_01);
        this.graph.set("WN-SCIT-02", WN_SCIT_02);
        this.graph.set("WN-SCIT-03", WN_SCIT_03);
        this.graph.set("WN-FELS-01", WN_FELS_01);
        this.graph.set("WN-FELS-02", WN_FELS_02);
        this.graph.set("WN-CEEC-01", WN_CEEC_01);
        this.graph.set("WN-CEEC-02", WN_CEEC_02);
        this.graph.set("WN-CENTRAL-01", WN_CENTRAL_01);
        this.graph.set("WN-CENTRAL-02", WN_CENTRAL_02);
        this.graph.set("WN-CENTRAL-03", WN_CENTRAL_03);
        this.graph.set("WN-DR-01", WN_DR_01);
        this.graph.set("WN-DR-02", WN_DR_02);
        this.graph.set("WN-CHPL-01", WN_CHPL_01);
        this.graph.set("WN-CHPL-02", WN_CHPL_02);
        this.graph.set("WN-SP-01", WN_SP_01);
        this.graph.set("WN-SP-02", WN_SP_02);
        this.graph.set("WN-SUBO-01", WN_SUBO_01);
        this.graph.set("WN-SUBO-02", WN_SUBO_02);
        this.graph.set("WN-BK-01", WN_BK_01);
        this.graph.set("WN-AG-01", WN_AG_01);
        this.graph.set("WN-HOTEL-01", WN_HOTEL_01);
        this.graph.set("WN-HOTEL-02", WN_HOTEL_02);
        this.graph.set("WN-ND-01", WN_ND_01);
        this.graph.set("WN-JP-01", WN_JP_01);
        this.graph.set("WN-JP-02", WN_JP_02);
        this.graph.set("WN-SHTM-01", WN_SHTM_01);
        this.graph.set("WN-SHTM-02", WN_SHTM_02);
        this.graph.set("WN-SHTM-03", WN_SHTM_03);
        this.graph.set("WN-SSB-01", WN_SSB_01);
        this.graph.set("WN-SSB-02", WN_SSB_02);
        this.graph.set("WN-OAE-01", WN_OAE_01);
        this.graph.set("WN-OAE-02", WN_OAE_02);
        this.graph.set("WN-OAE-03", WN_OAE_03);
        this.graph.set("WN-AUD-01", WN_AUD_01);
        this.graph.set("WN-AUD-02", WN_AUD_02);
        this.graph.set("WN-AUD-03", WN_AUD_03);
        this.graph.set("WN-BG-01", WN_BG_01);
        this.graph.set("WN-BG-02", WN_BG_02);
        this.graph.set("WN-SL-01", WN_SL_01);
        this.graph.set("WN-SL-02", WN_SL_02);
        this.graph.set("WN-SL-03", WN_SL_03);
        this.graph.set("WN-BARN-02", WN_BARN_02);
        this.graph.set("WN-BARN-03", WN_BARN_03);
        this.graph.set("WN-SF-01", WN_SF_01);
        this.graph.set("WN-SF-02", WN_SF_02);
        this.graph.set("WN-SF-03", WN_SF_03);
        this.graph.set("WN-FSS-01", WN_FSS_01);
        this.graph.set("WN-FSS-02", WN_FSS_02);
        this.graph.set("WN-FSS-03", WN_FSS_03);
        this.graph.set("WN-JB-01", WN_JB_01);
        this.graph.set("WN-JB-02", WN_JB_02);
        this.graph.set("WN-JB-03", WN_JB_03);
        this.graph.set("WN-JB-04", WN_JB_04);
        this.graph.set("WN-JB-05", WN_JB_05);
        this.graph.set("WN-JB-06", WN_JB_06);
        this.graph.set("WN-JB-07", WN_JB_07);
        this.graph.set("WN-JB-08", WN_JB_08);
        this.graph.set("WN-JB-09", WN_JB_09);
        this.graph.set("WN-HR-01", WN_HR_01);
        this.graph.set("WN-HR-02", WN_HR_02);
        this.graph.set("WN-HR-03", WN_HR_03);
        this.graph.set("WN-HR-04", WN_HR_04);
        this.graph.set("WN-UCR-01", WN_UCR_01);
        this.graph.set("WN-UCR-02", WN_UCR_02);
        this.graph.set("WN-UCR-03", WN_UCR_03);
        this.graph.set("WN-UCR-04", WN_UCR_04);
        this.graph.set("WN-UCR-05", WN_UCR_05);
        this.graph.set("WN-UCR-07", WN_UCR_07);
        this.graph.set("WN-UCR-08", WN_UCR_08);
        this.graph.set("WN-ESR-01", WN_ESR_01);
        this.graph.set("WN-ESR-02", WN_ESR_02);
        this.graph.set("WN-ESR-03", WN_ESR_03);
        this.graph.set("WN-ESR-04", WN_ESR_04);
        this.graph.set("WN-ESR-05", WN_ESR_05);
        this.graph.set("WN-WCR-01", WN_WCR_01);
        this.graph.set("WN-WCR-02", WN_WCR_02);
        this.graph.set("WN-WCR-03", WN_WCR_03);
        this.graph.set("WN-WCR-04", WN_WCR_04);
        this.graph.set("WN-WCR-05", WN_WCR_05);
        this.graph.set("WN-SB-01", WN_SB_01);
        this.graph.set("WN-SB-02", WN_SB_02);
        this.graph.set("WN-SB-03", WN_SB_03);
        this.graph.set("WN-SB-04", WN_SB_04);
        this.graph.set("WN-CCC-01", WN_CCC_01);
        this.graph.set("WN-CCC-02", WN_CCC_02);
        this.graph.set("WN-CCC-03", WN_CCC_03);
        this.graph.set("WN-CCC-04", WN_CCC_04);
        this.graph.set("WN-CCC-05", WN_CCC_05);
        this.graph.set("WN-SWC-01", WN_SWC_01);
        this.graph.set("WN-SWC-02", WN_SWC_02);
        this.graph.set("WN-SWC-04", WN_SWC_04);
        this.graph.set("WN-SWC-05", WN_SWC_05);
        this.graph.set("WN-NEC-01", WN_NEC_01);
        this.graph.set("WN-NEC-02", WN_NEC_02);
        this.graph.set("WN-NEC-03", WN_NEC_03);
        this.graph.set("WN-NEC-04", WN_NEC_04);
        this.graph.set("WN-NEC-05", WN_NEC_05);
        this.graph.set("WN-CML-02", WN_CML_02);
        this.graph.set("WN-SB-05", WN_SB_05);
        this.graph.set("WN-DC-01", WN_DC_01);
        this.graph.set("WN-DC-02", WN_DC_02);
        this.graph.set("WN-DC-03", WN_DC_03);
        this.graph.set("WN-SBA-03", WN_SBA_03);
        this.graph.set("WN-SOE-04", WN_SOE_04);
        this.graph.set("WN-DC-04", WN_DC_04);
        this.graph.set("WN-SF-04", WN_SF_04);
        this.graph.set("WN-GA-01", WN_GA_01);
        this.graph.set("WN-GA-02", WN_GA_02);
        this.graph.set("WN-SHTM-04", WN_SHTM_04);
        this.graph.set("WN-JB-10", WN_JB_10);
        this.graph.set("WN-BA-01", WN_BA_01);
        this.graph.set("WN-BA-02", WN_BA_02);
        this.graph.set("WN-JB-11", WN_JB_11);
        this.graph.set("WN-MAB-04", WN_MAB_04);
        this.graph.set("WN-STA-01", WN_STA_01);
        this.graph.set("WN-STA-02", WN_STA_02);
        this.graph.set("WN-STA-03", WN_STA_03);
        this.graph.set("WN-SHTM-05", WN_SHTM_05);
        this.graph.set("WN-NCB-01", WN_NCB_01);
        this.graph.set("Andrea Groceries", Andrea_Groceries);
        this.graph.set("Faculty of Law (FOL)", Faculty_of_Law);

        // Connections
        School_of_Engineering.addBidirectionalNeighbor(WN_SOE_02);
        School_of_Engineering.addBidirectionalNeighbor(WN_SOE_03);
        School_of_Engineering.addBidirectionalNeighbor(WN_SOE_04);
        School_of_Engineering.addBidirectionalNeighbor(WN_CEEC_01);
        School_of_Engineering.addBidirectionalNeighbor(WN_SOE_01);
        School_of_Computing_and_.addBidirectionalNeighbor(WN_SCIT_01);
        College_of_Health_Scienc.addBidirectionalNeighbor(WN_CHS_03);
        College_of_Health_Scienc.addBidirectionalNeighbor(WN_CHS_02);
        College_of_Health_Scienc.addBidirectionalNeighbor(WN_CHS_01);
        Faculty_of_Built_Environ.addBidirectionalNeighbor(WN_FBE_01);
        Faculty_of_Built_Environ.addBidirectionalNeighbor(WN_FBE_03);
        Faculty_of_Built_Environ.addBidirectionalNeighbor(WN_FBE_02);
        Faculty_of_Built_Environ.addBidirectionalNeighbor(WN_DC_02);
        School_of_Business_Admin.addBidirectionalNeighbor(WN_SBA_01);
        School_of_Business_Admin.addBidirectionalNeighbor(WN_SBA_02);
        School_of_Business_Admin.addBidirectionalNeighbor(WN_SBA_03);
        College_of_Business_Mana.addBidirectionalNeighbor(WN_CBM_02);
        Faculty_of_Sports_and_Sc.addBidirectionalNeighbor(WN_FSS_03);
        Faculty_of_Sports_and_Sc.addBidirectionalNeighbor(WN_FSS_02);
        Faculty_of_Education_and.addBidirectionalNeighbor(WN_CCC_03);
        Faculty_of_Education_and.addBidirectionalNeighbor(WN_FELS_02);
        Faculty_of_Education_and.addBidirectionalNeighbor(WN_JB_05);
        Faculty_of_Education_and.addBidirectionalNeighbor(WN_FELS_01);
        Main_Administration_Buil.addBidirectionalNeighbor(WN_MAB_03);
        Student_Union_Business_O.addBidirectionalNeighbor(WN_SUBO_01);
        Student_Union_Business_O.addBidirectionalNeighbor(WN_SUBO_02);
        Nursing_Department.addBidirectionalNeighbor(WN_ND_01);
        School_of_Hospitality_an.addBidirectionalNeighbor(WN_SHTM_02);
        School_of_Hospitality_an.addBidirectionalNeighbor(WN_SHTM_03);
        School_of_Hospitality_an.addBidirectionalNeighbor(WN_SHTM_01);
        Computing_and_Engineerin.addBidirectionalNeighbor(WN_CEEC_01);
        Computing_and_Engineerin.addBidirectionalNeighbor(WN_CEEC_02);
        Computing_and_Engineerin.addBidirectionalNeighbor(WN_ESR_04);
        Shared_Facilities.addBidirectionalNeighbor(WN_SF_03);
        Shared_Facilities.addBidirectionalNeighbor(WN_SF_02);
        Drawing_Room.addBidirectionalNeighbor(WN_DR_02);
        Chapel.addBidirectionalNeighbor(WN_CHPL_01);
        Auditorium.addBidirectionalNeighbor(WN_AUD_03);
        Auditorium.addBidirectionalNeighbor(WN_AUD_01);
        Auditorium.addBidirectionalNeighbor(WN_AUD_02);
        Calvin_McKain_Library.addBidirectionalNeighbor(WN_CML_03);
        The_Barn_UTech_Student_A.addBidirectionalNeighbor(WN_BARN_03);
        The_Barn_UTech_Student_A.addBidirectionalNeighbor(WN_BARN_02);
        Hotel.addBidirectionalNeighbor(WN_HOTEL_02);
        Hotel.addBidirectionalNeighbor(WN_SHTM_04);
        Burger_King.addBidirectionalNeighbor(WN_BK_01);
        Juici_Patties.addBidirectionalNeighbor(WN_JP_01);
        Juici_Patties.addBidirectionalNeighbor(WN_JP_02);
        Office_of_Admissions_and.addBidirectionalNeighbor(WN_OAE_03);
        Student_Services_Buildin.addBidirectionalNeighbor(WN_SSB_02);
        Student_Services_Buildin.addBidirectionalNeighbor(WN_SSB_01);
        Sculpture_Park.addBidirectionalNeighbor(WN_CENTRAL_03);
        Sculpture_Park.addBidirectionalNeighbor(WN_JB_07);
        NCB.addBidirectionalNeighbor(WN_NCB_01);
        Scholarship_Unit.addBidirectionalNeighbor(WN_SL_02);
        First_Gate.addBidirectionalNeighbor(WN_MAIN_01);
        Back_Gate.addBidirectionalNeighbor(WN_BG_01);
        Second_Gate.addBidirectionalNeighbor(WN_SECOND_01);
        WN_MAIN_01.addBidirectionalNeighbor(WN_MAIN_02);
        WN_MAIN_01.addBidirectionalNeighbor(WN_CML_01);
        WN_MAIN_02.addBidirectionalNeighbor(WN_MAIN_03);
        WN_MAIN_02.addBidirectionalNeighbor(WN_CML_01);
        WN_MAIN_03.addBidirectionalNeighbor(WN_JB_01);
        WN_MAIN_03.addBidirectionalNeighbor(WN_CML_02);
        WN_SECOND_01.addBidirectionalNeighbor(WN_SECOND_02);
        WN_SECOND_01.addBidirectionalNeighbor(WN_CML_01);
        WN_SECOND_02.addBidirectionalNeighbor(WN_SB_01);
        WN_CML_03.addBidirectionalNeighbor(WN_CML_02);
        WN_CML_03.addBidirectionalNeighbor(WN_SB_01);
        WN_CHS_01.addBidirectionalNeighbor(WN_HR_03);
        WN_CHS_02.addBidirectionalNeighbor(WN_SB_05);
        WN_CHS_03.addBidirectionalNeighbor(WN_JB_02);
        WN_FBE_01.addBidirectionalNeighbor(WN_FBE_03);
        WN_FBE_01.addBidirectionalNeighbor(WN_JB_02);
        WN_FBE_02.addBidirectionalNeighbor(WN_WCR_04);
        WN_FBE_02.addBidirectionalNeighbor(WN_DC_04);
        WN_FBE_03.addBidirectionalNeighbor(WN_SBA_02);
        WN_FBE_03.addBidirectionalNeighbor(WN_SBA_03);
        WN_CBM_02.addBidirectionalNeighbor(WN_JB_04);
        WN_CBM_02.addBidirectionalNeighbor(WN_HR_02);
        WN_CBM_02.addBidirectionalNeighbor(WN_SBA_01);
        WN_MAB_03.addBidirectionalNeighbor(WN_SCIT_03);
        WN_MAB_03.addBidirectionalNeighbor(WN_SB_05);
        WN_MAB_03.addBidirectionalNeighbor(WN_MAB_04);
        WN_SBA_01.addBidirectionalNeighbor(WN_JB_04);
        WN_SBA_01.addBidirectionalNeighbor(WN_HR_04);
        WN_SBA_02.addBidirectionalNeighbor(WN_HR_02);
        WN_SOE_01.addBidirectionalNeighbor(WN_ESR_02);
        WN_SOE_01.addBidirectionalNeighbor(WN_ESR_01);
        WN_SOE_02.addBidirectionalNeighbor(WN_SOE_03);
        WN_SOE_02.addBidirectionalNeighbor(WN_SCIT_03);
        WN_SOE_02.addBidirectionalNeighbor(WN_CCC_04);
        WN_SOE_03.addBidirectionalNeighbor(WN_SOE_04);
        WN_SOE_03.addBidirectionalNeighbor(WN_SCIT_03);
        WN_SCIT_01.addBidirectionalNeighbor(WN_FELS_02);
        WN_SCIT_01.addBidirectionalNeighbor(WN_SCIT_02);
        WN_SCIT_01.addBidirectionalNeighbor(WN_SCIT_03);
        WN_SCIT_02.addBidirectionalNeighbor(WN_JB_04);
        WN_SCIT_03.addBidirectionalNeighbor(WN_SB_05);
        WN_SCIT_03.addBidirectionalNeighbor(WN_SOE_04);
        WN_SCIT_03.addBidirectionalNeighbor(WN_FELS_02);
        WN_SCIT_03.addBidirectionalNeighbor(WN_CCC_04);
        WN_FELS_01.addBidirectionalNeighbor(WN_SP_01);
        WN_FELS_02.addBidirectionalNeighbor(WN_CENTRAL_02);
        WN_CEEC_02.addBidirectionalNeighbor(WN_ESR_03);
        WN_CENTRAL_01.addBidirectionalNeighbor(WN_JB_04);
        WN_CENTRAL_01.addBidirectionalNeighbor(WN_CCC_03);
        WN_CENTRAL_02.addBidirectionalNeighbor(WN_SP_01);
        WN_CENTRAL_02.addBidirectionalNeighbor(WN_CCC_04);
        WN_CENTRAL_02.addBidirectionalNeighbor(WN_JB_07);
        WN_CENTRAL_03.addBidirectionalNeighbor(WN_SP_02);
        WN_CENTRAL_03.addBidirectionalNeighbor(WN_JB_06);
        WN_DR_01.addBidirectionalNeighbor(WN_DR_02);
        WN_DR_01.addBidirectionalNeighbor(WN_NEC_01);
        WN_DR_02.addBidirectionalNeighbor(WN_JB_07);
        WN_CHPL_01.addBidirectionalNeighbor(WN_SUBO_02);
        WN_CHPL_01.addBidirectionalNeighbor(WN_SP_02);
        WN_CHPL_02.addBidirectionalNeighbor(WN_BK_01);
        WN_CHPL_02.addBidirectionalNeighbor(WN_SP_02);
        WN_CHPL_02.addBidirectionalNeighbor(WN_CCC_03);
        WN_SP_01.addBidirectionalNeighbor(WN_BA_01);
        WN_SP_01.addBidirectionalNeighbor(WN_JB_06);
        WN_SUBO_01.addBidirectionalNeighbor(WN_SHTM_03);
        WN_BK_01.addBidirectionalNeighbor(WN_JB_10);
        WN_AG_01.addBidirectionalNeighbor(WN_UCR_05);
        WN_AG_01.addBidirectionalNeighbor(WN_SHTM_01);
        WN_AG_01.addBidirectionalNeighbor(WN_JB_09);
        WN_HOTEL_01.addBidirectionalNeighbor(WN_BARN_02);
        WN_HOTEL_01.addBidirectionalNeighbor(WN_UCR_08);
        WN_HOTEL_01.addBidirectionalNeighbor(WN_ND_01);
        WN_HOTEL_01.addBidirectionalNeighbor(WN_GA_01);
        WN_HOTEL_02.addBidirectionalNeighbor(WN_GA_01);
        WN_ND_01.addBidirectionalNeighbor(WN_GA_02);
        WN_JP_01.addBidirectionalNeighbor(WN_JB_08);
        WN_JP_02.addBidirectionalNeighbor(WN_JB_09);
        WN_SHTM_01.addBidirectionalNeighbor(WN_SHTM_04);
        WN_SHTM_02.addBidirectionalNeighbor(WN_JB_10);
        WN_SHTM_02.addBidirectionalNeighbor(WN_SHTM_03);
        WN_SHTM_03.addBidirectionalNeighbor(WN_SHTM_05);
        WN_SSB_01.addBidirectionalNeighbor(WN_STA_02);
        WN_SSB_02.addBidirectionalNeighbor(WN_NEC_02);
        WN_OAE_01.addBidirectionalNeighbor(WN_NEC_02);
        WN_OAE_01.addBidirectionalNeighbor(WN_OAE_02);
        WN_OAE_02.addBidirectionalNeighbor(WN_NEC_03);
        WN_OAE_03.addBidirectionalNeighbor(WN_ESR_01);
        WN_AUD_01.addBidirectionalNeighbor(WN_UCR_05);
        WN_AUD_02.addBidirectionalNeighbor(WN_UCR_02);
        WN_AUD_03.addBidirectionalNeighbor(WN_UCR_05);
        WN_BG_01.addBidirectionalNeighbor(WN_NEC_05);
        WN_BG_02.addBidirectionalNeighbor(WN_NEC_04);
        WN_BG_02.addBidirectionalNeighbor(WN_NEC_05);
        WN_SL_01.addBidirectionalNeighbor(Faculty_of_Law);
        WN_SL_01.addBidirectionalNeighbor(WN_UCR_04);
        WN_SL_01.addBidirectionalNeighbor(WN_NEC_04);
        WN_SL_02.addBidirectionalNeighbor(WN_UCR_04);
        WN_SL_02.addBidirectionalNeighbor(WN_UCR_03);
        WN_SL_03.addBidirectionalNeighbor(WN_NEC_03);
        WN_SL_03.addBidirectionalNeighbor(WN_UCR_04);
        WN_BARN_03.addBidirectionalNeighbor(WN_WCR_01);
        WN_BARN_03.addBidirectionalNeighbor(WN_GA_01);
        WN_SF_01.addBidirectionalNeighbor(WN_WCR_01);
        WN_SF_01.addBidirectionalNeighbor(WN_SF_04);
        WN_SF_02.addBidirectionalNeighbor(WN_SWC_05);
        WN_SF_02.addBidirectionalNeighbor(WN_JB_11);
        WN_SF_03.addBidirectionalNeighbor(WN_HR_01);
        WN_SF_03.addBidirectionalNeighbor(WN_CCC_01);
        WN_SF_03.addBidirectionalNeighbor(WN_BA_02);
        WN_FSS_01.addBidirectionalNeighbor(WN_WCR_05);
        WN_FSS_01.addBidirectionalNeighbor(WN_FSS_03);
        WN_FSS_02.addBidirectionalNeighbor(WN_FSS_03);
        WN_JB_01.addBidirectionalNeighbor(WN_JB_02);
        WN_JB_01.addBidirectionalNeighbor(WN_WCR_04);
        WN_JB_02.addBidirectionalNeighbor(WN_JB_03);
        WN_JB_03.addBidirectionalNeighbor(WN_SBA_03);
        WN_JB_04.addBidirectionalNeighbor(WN_JB_05);
        WN_JB_04.addBidirectionalNeighbor(WN_HR_04);
        WN_JB_06.addBidirectionalNeighbor(WN_JB_07);
        WN_JB_07.addBidirectionalNeighbor(WN_JB_08);
        WN_JB_07.addBidirectionalNeighbor(WN_SHTM_05);
        WN_JB_08.addBidirectionalNeighbor(WN_SHTM_05);
        WN_JB_08.addBidirectionalNeighbor(WN_STA_03);
        WN_JB_08.addBidirectionalNeighbor(WN_NCB_01);
        WN_JB_09.addBidirectionalNeighbor(Andrea_Groceries);
        WN_HR_01.addBidirectionalNeighbor(WN_WCR_03);
        WN_HR_01.addBidirectionalNeighbor(WN_WCR_02);
        WN_HR_02.addBidirectionalNeighbor(WN_DC_02);
        WN_HR_02.addBidirectionalNeighbor(WN_DC_03);
        WN_HR_03.addBidirectionalNeighbor(WN_SB_05);
        WN_HR_03.addBidirectionalNeighbor(WN_HR_04);
        WN_HR_03.addBidirectionalNeighbor(WN_SBA_03);
        WN_HR_03.addBidirectionalNeighbor(WN_MAB_04);
        WN_UCR_01.addBidirectionalNeighbor(WN_UCR_05);
        WN_UCR_01.addBidirectionalNeighbor(WN_UCR_02);
        WN_UCR_02.addBidirectionalNeighbor(WN_UCR_03);
        WN_UCR_03.addBidirectionalNeighbor(WN_STA_01);
        WN_UCR_05.addBidirectionalNeighbor(WN_UCR_07);
        WN_UCR_07.addBidirectionalNeighbor(WN_UCR_08);
        WN_UCR_07.addBidirectionalNeighbor(WN_GA_02);
        WN_ESR_01.addBidirectionalNeighbor(WN_ESR_02);
        WN_ESR_01.addBidirectionalNeighbor(WN_ESR_03);
        WN_ESR_01.addBidirectionalNeighbor(WN_NEC_02);
        WN_ESR_02.addBidirectionalNeighbor(WN_CCC_04);
        WN_ESR_04.addBidirectionalNeighbor(WN_ESR_05);
        WN_ESR_05.addBidirectionalNeighbor(WN_SB_05);
        WN_WCR_01.addBidirectionalNeighbor(WN_JB_11);
        WN_WCR_03.addBidirectionalNeighbor(WN_SWC_05);
        WN_WCR_03.addBidirectionalNeighbor(WN_DC_01);
        WN_WCR_04.addBidirectionalNeighbor(WN_SWC_01);
        WN_WCR_04.addBidirectionalNeighbor(WN_WCR_05);
        WN_SB_01.addBidirectionalNeighbor(WN_SB_02);
        WN_SB_02.addBidirectionalNeighbor(WN_SB_03);
        WN_SB_03.addBidirectionalNeighbor(WN_SB_04);
        WN_SB_03.addBidirectionalNeighbor(WN_CML_02);
        WN_SB_04.addBidirectionalNeighbor(WN_SB_05);
        WN_CCC_01.addBidirectionalNeighbor(WN_SF_04);
        WN_CCC_01.addBidirectionalNeighbor(WN_GA_01);
        WN_CCC_01.addBidirectionalNeighbor(WN_CCC_02);
        WN_CCC_02.addBidirectionalNeighbor(WN_CCC_03);
        WN_CCC_02.addBidirectionalNeighbor(WN_BA_02);
        WN_CCC_03.addBidirectionalNeighbor(WN_DC_03);
        WN_CCC_03.addBidirectionalNeighbor(WN_BA_02);
        WN_CCC_03.addBidirectionalNeighbor(WN_BA_01);
        WN_CCC_04.addBidirectionalNeighbor(WN_CCC_05);
        WN_CCC_05.addBidirectionalNeighbor(WN_NEC_01);
        WN_SWC_01.addBidirectionalNeighbor(WN_SWC_02);
        WN_SWC_01.addBidirectionalNeighbor(WN_DC_01);
        WN_SWC_02.addBidirectionalNeighbor(WN_SWC_04);
        WN_SWC_04.addBidirectionalNeighbor(WN_SWC_05);
        WN_NEC_01.addBidirectionalNeighbor(WN_NEC_02);
        WN_SB_05.addBidirectionalNeighbor(WN_SOE_04);
        WN_DC_01.addBidirectionalNeighbor(WN_DC_04);
        WN_DC_02.addBidirectionalNeighbor(WN_DC_04);
        WN_GA_01.addBidirectionalNeighbor(WN_JB_10);
        WN_SHTM_04.addBidirectionalNeighbor(WN_JB_10);
        WN_STA_01.addBidirectionalNeighbor(WN_STA_02);
        WN_STA_02.addBidirectionalNeighbor(WN_NCB_01);
        WN_STA_03.addBidirectionalNeighbor(WN_NCB_01);
    }

    getgraph() { return this.graph; }
    getNode(name) { return this.graph.get(name); }
    getAllNodes() { return Array.from(this.graph.values()); }
    getAllBuildings() { return Array.from(this.graph.values()).filter(n => n.type === 'building'); }
    getAllWalkways() { return Array.from(this.graph.values()).filter(n => n.type === 'walkway'); }
}

export { GraphDatabase };